version: '3.8'
services:
    listvehiclesapi:
        build:
            context: ./listvehiclesapi
            target: development
        volumes:
            - ./listvehiclesapi:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8000:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    vehicletracking:
        build:
            context: ./VehicleTracking
            target: development
        volumes:
            - ./VehicleTracking:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
    geolocalisation:
        build:
            context: ./ServiceGeolocalisation
            target: development
        volumes:
            - ./ServiceGeolocalisation:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8002:8002"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
