version: '3.8'
services:
    payment:
        build:
            context: ./payment
            target: development
        volumes:
            - ./payment:/src
            - /src/node_modules
        command: npm run start
        ports:
            - "8500:8500"
        environment: 
            NODE_ENV: development
            DEBUG: src:*