version: '3.8'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
    
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    template:
        build:
            context: ./template
            target: development
        volumes:
            - ./template:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8000:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
<<<<<<< HEAD
    user:
        build:
            context: ./user
            target: development
        volumes:
            - ./user:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8100:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
=======
    log:
        build:
            context: ./log
            target: development
        volumes:
            - ./log:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8003:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    vehicletracking:
        build:
            context: ./VehicleTracking
            target: development
        volumes:
            - ./VehicleTracking:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
    borne:
        build:
            context: ./borne
            target: development
        volumes:
            - ./borne:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8200:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    vehicule:
        build:
            context: ./vehicule
            target: development
        volumes:
            - ./vehicule:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8300:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*