version: '3.8'
services:
    listvehiclesapi:
        build:
            context: ./listvehiclesapi
            target: development
        volumes:
            - ./listvehiclesapi:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8081:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    vehicleTracking:
        build:
            context: ./VehicleTracking
            target: development
        volumes:
            - ./VehicleTracking:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
    utilisateur:
        build:
            context: ./utilisateur
            target: development
        volumes:
            - ./utilisateur:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8100:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
