version: '3.8'
services:
#Services du Volet Surveillance 
    vehicles:
        build:
            context: ./vehicles
            target: development
        volumes:
            - ./vehicles:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8000:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    tracking:
        build:
            context: ./tracking
            target: development
        volumes:
            - ./tracking:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
    geolocalisation:
        build:
            context: ./ServiceGeolocalisation
            target: development
        volumes:
            - ./ServiceGeolocalisation:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8002:8002"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
