version: '3.8'
services:
    template:
        build:
            context: ./template
            target: development
        volumes:
            - ./template:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8000:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*

    gestion_taches_agent:
        build:
            context: ./gestion_taches_agent
            target: development
        volumes:
            - ./gestion_taches_agent:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*

