version: '3.8'
services:
#Services du Volet Surveillance 
    vehicles:
        build:
            context: ./vehicles
            target: development
        volumes:
            - ./vehicles:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8081:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    tracking:
        build:
            context: ./tracking
            target: development
        volumes:
            - ./tracking:/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*    
    geolocalisation:
        build:
            context: ./geolocalisation
            target: development
        volumes:
            - ./geolocalisation::/src
            - /src/node_modules
        command: npm run start:dev
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*   
        
