version: '3.8'
services:
    payment:
        build:
            context: ./payment
            target: development
        volumes:
            - ./payment:/src
            - /src/node_modules
        command: npm run start
        ports:
            - "8000:8000"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    create_facture:
        build:
            context: ./create-facture
            target: development
        volumes:
            - ./create-facture:/src
            - /src/node_modules
        command: npm run start
        ports:
            - "8001:8001"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    pricing_service:
        build:
            context: ./pricing-service
            target: development
        volumes:
            - ./pricing-service:/src
            - /src/node_modules
        command: npm run start
        ports:
            - "8002:8002"
        environment: 
            NODE_ENV: development
            DEBUG: src:*
    rental_service:
        build:
            context: ./rental-service
            target: development
        volumes:
            - ./rental-service:/src
            - /src/node_modules
        command: npm run start
        ports:
            - "8003:8003"
        environment: 
            NODE_ENV: development
            DEBUG: src:*